/* ============ 高频词汇扩充 ============ */
const VOCAB_EXTRA = [
  // 自然环境类
  { cat: "自然环境类", en: "pollution", zh: "污染" },
  { cat: "自然环境类", en: "sustainability", zh: "可持续性" },
  { cat: "自然环境类", en: "conservation", zh: "（资源）保护" },
  { cat: "自然环境类", en: "renewable energy", zh: "可再生能源" },
  { cat: "自然环境类", en: "ecosystem", zh: "生态系统" },
  { cat: "自然环境类", en: "carbon emissions", zh: "碳排放" },
  { cat: "自然环境类", en: "waste sorting", zh: "垃圾分类" },
  { cat: "自然环境类", en: "green development", zh: "绿色发展" },
  // 科技创新类
  { cat: "科技创新类", en: "digitalization", zh: "数字化" },
  { cat: "科技创新类", en: "automation", zh: "自动化" },
  { cat: "科技创新类", en: "cutting-edge technology", zh: "前沿技术" },
  { cat: "科技创新类", en: "e-commerce", zh: "电子商务" },
  { cat: "科技创新类", en: "smart device", zh: "智能设备" },
  { cat: "科技创新类", en: "online learning", zh: "在线学习" },
  { cat: "科技创新类", en: "information technology", zh: "信息技术" },
  // 社会热点类
  { cat: "社会热点类", en: "inequality", zh: "不平等" },
  { cat: "社会热点类", en: "unemployment", zh: "失业" },
  { cat: "社会热点类", en: "urbanization", zh: "城市化" },
  { cat: "社会热点类", en: "social welfare", zh: "社会福利" },
  { cat: "社会热点类", en: "public health", zh: "公共卫生" },
  { cat: "社会热点类", en: "mental health", zh: "心理健康" },
  { cat: "社会热点类", en: "an aging society", zh: "老龄化社会" },
  { cat: "社会热点类", en: "employment pressure", zh: "就业压力" },
  // 文化类
  { cat: "文化类", en: "globalization", zh: "全球化" },
  { cat: "文化类", en: "preserve traditions", zh: "保护传统" },
  { cat: "文化类", en: "traditional festival", zh: "传统节日" },
  { cat: "文化类", en: "cultural soft power", zh: "文化软实力" },
  { cat: "文化类", en: "cultural symbols", zh: "文化符号" },
  // 成长教育类
  { cat: "成长教育类", en: "academic performance", zh: "学业表现" },
  { cat: "成长教育类", en: "educational equity", zh: "教育公平" },
  { cat: "成长教育类", en: "quality education", zh: "素质教育" },
  { cat: "成长教育类", en: "well-rounded development", zh: "全面发展" },
  { cat: "成长教育类", en: "knowledge acquisition", zh: "知识获取" },
  { cat: "成长教育类", en: "practical ability", zh: "实践能力" },
  // 个人发展类
  { cat: "个人发展类", en: "integrity", zh: "正直、诚信" },
  { cat: "个人发展类", en: "resilience", zh: "韧性、抗挫力" },
  { cat: "个人发展类", en: "a sense of responsibility", zh: "责任感" },
  { cat: "个人发展类", en: "teamwork spirit", zh: "团队精神" },
  { cat: "个人发展类", en: "self-confidence", zh: "自信" },
  { cat: "个人发展类", en: "persistence", zh: "持之以恒" },
  // 高分替换词（写作提分）
  { cat: "高分替换词", en: "important → significant / crucial", zh: "重要的" },
  { cat: "高分替换词", en: "many → numerous / a host of", zh: "许多" },
  { cat: "高分替换词", en: "think → deem / hold the view", zh: "认为" },
  { cat: "高分替换词", en: "show → illustrate / demonstrate", zh: "表明" },
  { cat: "高分替换词", en: "cause → give rise to / trigger", zh: "引起" },
  { cat: "高分替换词", en: "use → utilize / make use of", zh: "使用" },
  { cat: "高分替换词", en: "help → facilitate / contribute to", zh: "有助于" },
  { cat: "高分替换词", en: "so → consequently / therefore", zh: "因此" },
  { cat: "高分替换词", en: "but → nevertheless / whereas", zh: "但是" },
  { cat: "高分替换词", en: "get → obtain / acquire", zh: "获得" },
  { cat: "高分替换词", en: "big → enormous / tremendous", zh: "巨大的" },
  { cat: "高分替换词", en: "good → beneficial / rewarding", zh: "好的" },
];
