/* ============ 阅读生词库（两次阅读生词汇总） ============ */
/* 来源：阅读生词表①（2015）+ ②（2016）+ ③（2017），均为英语一 Text1–4 */
/* 三分类：阅读·熟词僻义 / 阅读生词 / 阅读短语 */

const VOCAB_READING = [
  /* ---------- 阅读 · 熟词僻义 ---------- */
  { cat: "阅读·熟词僻义", src: "① 2015", en: "apparent", zh: "表面上的；貌似的（常见义：明显的）" },  { cat: "阅读·熟词僻义", src: "① 2015", en: "taste", zh: "爱好，品味（常见义：味道）" },  { cat: "阅读·熟词僻义", src: "① 2015", en: "maintain", zh: "坚持认为；维护（常见义：维持）" },  { cat: "阅读·熟词僻义", src: "① 2015", en: "monarch-infested", zh: "君主遍布的（infest 常见义：侵扰）" },  { cat: "阅读·熟词僻义", src: "① 2015", en: "warrant", zh: "搜查令，授权令（常见义：保证）" },  { cat: "阅读·熟词僻义", src: "① 2015", en: "refrain", zh: "克制，避免（常见义：副歌）" },  { cat: "阅读·熟词僻义", src: "① 2015", en: "modest", zh: "不大的；保守的（常见义：谦虚的）" },  { cat: "阅读·熟词僻义", src: "① 2015", en: "lame", zh: "站不住脚的（常见义：跛的）" },  { cat: "阅读·熟词僻义", src: "① 2015", en: "swallow", zh: "全盘接受，轻信（常见义：吞咽）" },  { cat: "阅读·熟词僻义", src: "① 2015", en: "novel", zh: "新颖的（常见义：小说）" },  { cat: "阅读·熟词僻义", src: "① 2015", en: "sweeping", zh: "影响广泛的；笼统的（常见义：扫除）" },  { cat: "阅读·熟词僻义", src: "① 2015", en: "ruling", zh: "裁决，判决（常见义：统治）" },  { cat: "阅读·熟词僻义", src: "① 2015", en: "cite", zh: "援引；传唤（常见义：引用）" },  { cat: "阅读·熟词僻义", src: "① 2015", en: "flagged up", zh: "标记出（flag 常见义：旗帜）" },  { cat: "阅读·熟词僻义", src: "① 2015", en: "engaging", zh: "聘请，聘用（常见义：迷人的）" },  { cat: "阅读·熟词僻义", src: "① 2015", en: "merit / merits", zh: "可取之处；案情是非；值得（常见义：优点）" },  { cat: "阅读·熟词僻义", src: "① 2015", en: "integrity", zh: "完整（性）（常见义：诚信）" },  { cat: "阅读·熟词僻义", src: "① 2015", en: "frames", zh: "构建；框定（常见义：框架）" },  { cat: "阅读·熟词僻义", src: "① 2015", en: "matter", zh: "重要，要紧（常见义：事情）" },  { cat: "阅读·熟词僻义", src: "① 2015", en: "betray", zh: "泄露，暴露（常见义：背叛）" },  { cat: "阅读·熟词僻义", src: "① 2015", en: "circulation", zh: "（报刊）发行量（常见义：循环）" },  { cat: "阅读·熟词僻义", src: "① 2015", en: "margin", zh: "利润；余地（常见义：边缘）" },  { cat: "阅读·熟词僻义", src: "① 2015", en: "concern", zh: "担忧，关切；涉及（常见义：关注）" },  { cat: "阅读·熟词僻义", src: "① 2015", en: "establishment", zh: "机构；权威集团（常见义：建立）" },  { cat: "阅读·熟词僻义", src: "② 2016", en: "employ", zh: "使用，运用（常见义：雇用）" },  { cat: "阅读·熟词僻义", src: "② 2016", en: "sanction", zh: "制裁；处罚（常见义：批准）" },  { cat: "阅读·熟词僻义", src: "② 2016", en: "regarding", zh: "关于，至于（regard 常见义：看待）" },  { cat: "阅读·熟词僻义", src: "② 2016", en: "material", zh: "物质的；有形的（常见义：材料）" },  { cat: "阅读·熟词僻义", src: "② 2016", en: "curious", zh: "奇特的，古怪的（常见义：好奇的）" },  { cat: "阅读·熟词僻义", src: "② 2016", en: "belts", zh: "地带，区域（常见义：腰带）" },  { cat: "阅读·熟词僻义", src: "② 2016", en: "concrete", zh: "具体的；实在的（常见义：混凝土）" },  { cat: "阅读·熟词僻义", src: "② 2016", en: "parties", zh: "政党，党派（常见义：聚会）" },  { cat: "阅读·熟词僻义", src: "② 2016", en: "sentiment", zh: "观点，看法（常见义：情感）" },  { cat: "阅读·熟词僻义", src: "② 2016", en: "equals", zh: "等同于（常见义：平等的）" },  { cat: "阅读·熟词僻义", src: "② 2016", en: "lobby", zh: "游说（团体）（常见义：大厅）" },  { cat: "阅读·熟词僻义", src: "② 2016", en: "sticks", zh: "固守，坚守（常见义：粘住）" },  { cat: "阅读·熟词僻义", src: "② 2016", en: "respects", zh: "方面（常见义：尊重）" },  { cat: "阅读·熟词僻义", src: "② 2016", en: "diffuse", zh: "广泛的（常见义：扩散）" },  { cat: "阅读·熟词僻义", src: "② 2016", en: "ditch", zh: "抛弃，丢弃（常见义：沟渠）" },  { cat: "阅读·熟词僻义", src: "② 2016", en: "dwarf", zh: "使相形见绌，远超（常见义：侏儒）" },  { cat: "阅读·熟词僻义", src: "② 2016", en: "overhead", zh: "运营开销（常见义：在头顶上）" },  { cat: "阅读·熟词僻义", src: "② 2016", en: "figure", zh: "弄清楚，认为（常见义：数字）" },  { cat: "阅读·熟词僻义", src: "② 2016", en: "legacy", zh: "遗留物；传统业务（常见义：遗产）" },  { cat: "阅读·熟词僻义", src: "② 2016", en: "luxury", zh: "难得的有利条件（常见义：奢侈品）" },  { cat: "阅读·熟词僻义", src: "② 2016", en: "impinge on", zh: "侵害，对……造成不良影响" },
  /* ---------- 阅读生词 ---------- */
  { cat: "阅读生词", src: "① 2015", en: "abdicate", zh: "退位，放弃（权力）" },  { cat: "阅读生词", src: "① 2015", en: "scandals", zh: "丑闻，丑事" },  { cat: "阅读生词", src: "① 2015", en: "polarised", zh: "两极分化的" },  { cat: "阅读生词", src: "① 2015", en: "embody", zh: "体现，使具体化" },  { cat: "阅读生词", src: "① 2015", en: "transcendence", zh: "超越，超脱" },  { cat: "阅读生词", src: "① 2015", en: "absolutist", zh: "专制主义的" },  { cat: "阅读生词", src: "① 2015", en: "counterparts", zh: "对应的人；地位相当者" },  { cat: "阅读生词", src: "① 2015", en: "indefensible", zh: "站不住脚的；无法辩护的" },  { cat: "阅读生词", src: "① 2015", en: "intrusiveness", zh: "侵扰；过度窥探" },  { cat: "阅读生词", src: "① 2015", en: "hierarchical", zh: "等级制度的；等级森严的" },  { cat: "阅读生词", src: "① 2015", en: "bizarre", zh: "怪异的，离奇的" },  { cat: "阅读生词", src: "① 2015", en: "strive", zh: "努力，力求，奋斗" },  { cat: "阅读生词", src: "① 2015", en: "downside", zh: "不利之处，缺点" },  { cat: "阅读生词", src: "① 2015", en: "recklessly", zh: "鲁莽地，轻率地" },  { cat: "阅读生词", src: "① 2015", en: "discernible", zh: "可识别的，看得出的" },  { cat: "阅读生词", src: "① 2015", en: "burdensome", zh: "繁重的，麻烦的" },  { cat: "阅读生词", src: "① 2015", en: "invalidate", zh: "使无效，废除" },  { cat: "阅读生词", src: "① 2015", en: "prohibition", zh: "禁止，禁令" },  { cat: "阅读生词", src: "① 2015", en: "correspondence", zh: "通信，往来信件" },  { cat: "阅读生词", src: "① 2015", en: "discarding", zh: "抛弃，摒弃" },  { cat: "阅读生词", src: "① 2015", en: "novel", zh: "新颖的（见熟词僻义）" },  { cat: "阅读生词", src: "① 2015", en: "scrutiny", zh: "仔细审查，核查" },  { cat: "阅读生词", src: "① 2015", en: "irreproducibility", zh: "不可再现性，无法重复" },  { cat: "阅读生词", src: "① 2015", en: "reproducibility", zh: "可再现性，可重复性" },  { cat: "阅读生词", src: "① 2015", en: "biostatistician", zh: "生物统计学家" },  { cat: "阅读生词", src: "① 2015", en: "methodology", zh: "方法论，研究方法" },  { cat: "阅读生词", src: "① 2015", en: "foresight", zh: "远见，先见之明" },  { cat: "阅读生词", src: "① 2015", en: "long-overdue", zh: "早就该实行的，姗姗来迟的" },  { cat: "阅读生词", src: "① 2015", en: "impelled", zh: "促使，推动" },  { cat: "阅读生词", src: "① 2015", en: "verify", zh: "核实，查证" },  { cat: "阅读生词", src: "① 2015", en: "unsettling", zh: "令人不安的，使人困扰的" },  { cat: "阅读生词", src: "① 2015", en: "dearth", zh: "缺乏，不足" },  { cat: "阅读生词", src: "① 2015", en: "conspiring", zh: "密谋，共谋" },  { cat: "阅读生词", src: "① 2015", en: "predecessor", zh: "前任；前辈" },  { cat: "阅读生词", src: "① 2015", en: "accountable", zh: "负有责任的，应承担责任的" },  { cat: "阅读生词", src: "① 2015", en: "doctrine", zh: "信条，教条，准则" },  { cat: "阅读生词", src: "① 2015", en: "mechanism", zh: "机制，机理" },  { cat: "阅读生词", src: "① 2015", en: "shareholder", zh: "股东" },  { cat: "阅读生词", src: "① 2015", en: "degraded", zh: "贬低；降级；退化" },  { cat: "阅读生词", src: "① 2015", en: "traceable", zh: "可追踪的，可查证的" },  { cat: "阅读生词", src: "① 2015", en: "revelation", zh: "爆料，揭示，真相披露" },  { cat: "阅读生词", src: "② 2016", en: "innovator", zh: "创新者，革新者" },  { cat: "阅读生词", src: "② 2016", en: "preliminary", zh: "初步的，预备的" },  { cat: "阅读生词", src: "② 2016", en: "incite", zh: "煽动，鼓动" },  { cat: "阅读生词", src: "② 2016", en: "uplifting", zh: "令人振奋的；鼓舞人心的" },  { cat: "阅读生词", src: "② 2016", en: "arbiter", zh: "仲裁者，裁决人" },  { cat: "阅读生词", src: "② 2016", en: "faintly", zh: "隐约地；微弱地" },  { cat: "阅读生词", src: "② 2016", en: "intangible", zh: "无形的，难以捉摸的" },  { cat: "阅读生词", src: "② 2016", en: "adornment", zh: "装饰，装饰品" },  { cat: "阅读生词", src: "② 2016", en: "idealized", zh: "理想化的" },  { cat: "阅读生词", src: "② 2016", en: "enforcement", zh: "执行，实施，强制手段" },  { cat: "阅读生词", src: "② 2016", en: "compliance", zh: "服从，遵从" },  { cat: "阅读生词", src: "② 2016", en: "persuasion", zh: "劝说，说服" },  { cat: "阅读生词", src: "② 2016", en: "elevate", zh: "提升；抬高" },  { cat: "阅读生词", src: "② 2016", en: "notion", zh: "观念，看法" },  { cat: "阅读生词", src: "② 2016", en: "dwellers", zh: "居民，居住者" },  { cat: "阅读生词", src: "② 2016", en: "guardianship", zh: "保护，守护；监护" },  { cat: "阅读生词", src: "② 2016", en: "explicitly", zh: "明确地，清楚地" },  { cat: "阅读生词", src: "② 2016", en: "authorising", zh: "授权，批准" },  { cat: "阅读生词", src: "② 2016", en: "intrusion", zh: "侵入，侵扰，闯入" },  { cat: "阅读生词", src: "② 2016", en: "renovation", zh: "翻新，整修" },  { cat: "阅读生词", src: "② 2016", en: "renewal", zh: "重建，更新；复兴" },  { cat: "阅读生词", src: "② 2016", en: "enviable", zh: "令人羡慕的" },  { cat: "阅读生词", src: "② 2016", en: "coherence", zh: "连贯性，整体性；条理" },  { cat: "阅读生词", src: "② 2016", en: "premise", zh: "前提，假设" },  { cat: "阅读生词", src: "② 2016", en: "prosecute", zh: "起诉，控告" },  { cat: "阅读生词", src: "② 2016", en: "bribery", zh: "行贿，贿赂" },  { cat: "阅读生词", src: "② 2016", en: "prosecution", zh: "起诉，检举" },  { cat: "阅读生词", src: "② 2016", en: "investigation", zh: "调查，侦查" },  { cat: "阅读生词", src: "② 2016", en: "comprehensive", zh: "全面的；综合的" },  { cat: "阅读生词", src: "② 2016", en: "lenient", zh: "（处罚）宽大的，宽容的" },  { cat: "阅读生词", src: "② 2016", en: "leniency", zh: "宽大处理，宽容" },  { cat: "阅读生词", src: "② 2016", en: "penalty", zh: "惩罚，处罚" },  { cat: "阅读生词", src: "② 2016", en: "substantial", zh: "大量的；实质性的" },  { cat: "阅读生词", src: "② 2016", en: "demonstrate", zh: "证明，证实" },  { cat: "阅读生词", src: "② 2016", en: "cease", zh: "停止，终止" },  { cat: "阅读生词", src: "② 2016", en: "nostalgia", zh: "怀旧，乡愁" },  { cat: "阅读生词", src: "② 2016", en: "rustle", zh: "沙沙声（纸张翻动声）" },  { cat: "阅读生词", src: "② 2016", en: "incentive", zh: "激励，诱因，动机" },  { cat: "阅读生词", src: "② 2016", en: "constraint", zh: "约束，限制条件" },  { cat: "阅读生词", src: "② 2016", en: "revenue", zh: "收入，收益" },  { cat: "阅读生词", src: "② 2016", en: "tremendous", zh: "巨大的，极大的" },  { cat: "阅读生词", src: "② 2016", en: "blunder", zh: "失误，愚蠢的错误" },  { cat: "阅读生词", src: "② 2016", en: "foresighted", zh: "有远见的，深谋远虑的" },  { cat: "阅读生词", src: "② 2016", en: "discontinue", zh: "停止，中止" },  { cat: "阅读生词", src: "② 2016", en: "obsessed", zh: "痴迷的，热衷的" },  { cat: "阅读生词", src: "② 2016", en: "digital-only", zh: "仅数字化的，纯线上的" },  { cat: "阅读生词", src: "② 2016", en: "subscription", zh: "订阅（服务）" },  { cat: "阅读生词", src: "② 2016", en: "streaming", zh: "（媒体）流媒体" },  { cat: "阅读生词", src: "② 2016", en: "corruption", zh: "腐败，贪污" },  { cat: "阅读生词", src: "② 2016", en: "corporate", zh: "公司的；企业的" },  { cat: "阅读生词", src: "② 2016", en: "monetary", zh: "货币的；金钱的" },  { cat: "阅读生词", src: "② 2016", en: "enviable", zh: "令人羡慕的" },
  /* ---------- 阅读短语 ---------- */
  { cat: "阅读短语", src: "② 2016", en: "account for", zh: "解释；占比" },  { cat: "阅读短语", src: "② 2016", en: "bank on", zh: "指望，依靠" },  { cat: "阅读短语", src: "② 2016", en: "engage in", zh: "从事，参与" },  { cat: "阅读短语", src: "② 2016", en: "regard … as …", zh: "把……看作……" },  { cat: "阅读短语", src: "② 2016", en: "be prosecuted for", zh: "因……遭到起诉" },  { cat: "阅读短语", src: "② 2016", en: "add value to", zh: "为……增值" },  { cat: "阅读短语", src: "② 2016", en: "take … as a signal", zh: "将……视作一种信号" },  { cat: "阅读短语", src: "② 2016", en: "halo effect", zh: "光环效应" },  { cat: "阅读短语", src: "② 2016", en: "have trouble (in) doing", zh: "做……有困难" },  { cat: "阅读短语", src: "② 2016", en: "rule out the possibility", zh: "排除可能性" },  { cat: "阅读短语", src: "② 2016", en: "contribute to", zh: "捐助；促成" },  { cat: "阅读短语", src: "② 2016", en: "in all", zh: "总而言之" },  { cat: "阅读短语", src: "② 2016", en: "based on its merits", zh: "根据案情本身" },  { cat: "阅读短语", src: "① 2015", en: "sort out", zh: "理清，弄明白，解决" },  { cat: "阅读短语", src: "② 2016", en: "in contrast to", zh: "与……形成对比" },  { cat: "阅读短语", src: "② 2016", en: "make sense", zh: "合乎情理，有意义" },  { cat: "阅读短语", src: "② 2016", en: "turn out to be", zh: "结果是，被证明是" },  { cat: "阅读短语", src: "② 2016", en: "in charge", zh: "主管，掌管，负责" },  { cat: "阅读短语", src: "② 2016", en: "in other words", zh: "换句话说，换言之" },  { cat: "阅读短语", src: "② 2016", en: "end up doing", zh: "最终做某事" },  { cat: "阅读短语", src: "② 2016", en: "aside from", zh: "撇开……不谈，除……之外" },  { cat: "阅读短语", src: "② 2016", en: "a matter of", zh: "关乎……的问题；取决于……" },  { cat: "阅读短语", src: "② 2016", en: "financial constraints", zh: "财务限制、资金约束" },  { cat: "阅读短语", src: "② 2016", en: "generate revenue", zh: "创造收益、产生收入" },  { cat: "阅读短语", src: "② 2016", en: "migrate away from", zh: "从……转移/离开" },  { cat: "阅读短语", src: "② 2016", en: "go about doing sth.", zh: "着手做某事" },  { cat: "阅读短语", src: "② 2016", en: "be willing to do", zh: "愿意做某事" },  { cat: "阅读短语", src: "② 2016", en: "ought to do", zh: "应当做……" },  { cat: "阅读短语", src: "② 2016", en: "plenty of", zh: "大量的，充足的" },  { cat: "阅读短语", src: "② 2016", en: "designed to do", zh: "旨在；目的是" },  { cat: "阅读短语", src: "② 2016", en: "get into trouble with the law", zh: "触犯法律，惹上官司" },  { cat: "阅读短语", src: "② 2016", en: "political campaigns", zh: "政治竞选活动" },  { cat: "阅读短语", src: "② 2016", en: "social responsibility", zh: "社会责任" },  { cat: "阅读短语", src: "② 2016", en: "aggressive strategy", zh: "激进的策略" },
  /* ---------- 第三批：2017 英语一 Text1–4 ---------- */
  { cat: "阅读·熟词僻义", src: "③ 2017", en: "advance", zh: "进展；v. 提出（观点）（常见义：前进；进步）" },
  { cat: "阅读·熟词僻义", src: "③ 2017", en: "demanding", zh: "苛刻的；费力的（常见义：要求（demand））" },
  { cat: "阅读·熟词僻义", src: "③ 2017", en: "providing", zh: "假如，如果（常见义：提供（provide））" },
  { cat: "阅读·熟词僻义", src: "③ 2017", en: "matter", zh: "要紧，有关系（常见义：事情；物质）" },
  { cat: "阅读·熟词僻义", src: "③ 2017", en: "figures", zh: "认为，估计（常见义：数字；人物）" },
  { cat: "阅读·熟词僻义", src: "③ 2017", en: "hit", zh: "达到；n. 打击（常见义：打击，撞击）" },
  { cat: "阅读·熟词僻义", src: "③ 2017", en: "conduct", zh: "行为，举止（常见义：进行，实施）" },
  { cat: "阅读·熟词僻义", src: "③ 2017", en: "concrete", zh: "具体的；实在的（常见义：混凝土）" },
  { cat: "阅读·熟词僻义", src: "③ 2017", en: "compact", zh: "契约，协定（常见义：紧凑的）" },
  { cat: "阅读·熟词僻义", src: "③ 2017", en: "rests", zh: "依赖，取决于（常见义：休息）" },
  { cat: "阅读·熟词僻义", src: "③ 2017", en: "measures", zh: "衡量，测量（常见义：措施）" },
  { cat: "阅读·熟词僻义", src: "③ 2017", en: "access", zh: "接触 / 获取的机会（常见义：通道，入口）" },
  { cat: "阅读生词", src: "③ 2017", en: "authorities", zh: "当局，官方" },
  { cat: "阅读生词", src: "③ 2017", en: "domestic", zh: "国内的；家庭的" },
  { cat: "阅读生词", src: "③ 2017", en: "flight", zh: "航班；飞行" },
  { cat: "阅读生词", src: "③ 2017", en: "private", zh: "私人的；私营的" },
  { cat: "阅读生词", src: "③ 2017", en: "massive", zh: "巨大的，大规模的" },
  { cat: "阅读生词", src: "③ 2017", en: "time-consuming", zh: "费时的，耗时的" },
  { cat: "阅读生词", src: "③ 2017", en: "procedures", zh: "程序，手续" },
  { cat: "阅读生词", src: "③ 2017", en: "terrorists", zh: "恐怖分子" },
  { cat: "阅读生词", src: "③ 2017", en: "tragic", zh: "悲惨的，悲剧的" },
  { cat: "阅读生词", src: "③ 2017", en: "drag", zh: "累赘，拖累；v. 拖拽" },
  { cat: "阅读生词", src: "③ 2017", en: "infuriating", zh: "令人愤怒的" },
  { cat: "阅读生词", src: "③ 2017", en: "investigators", zh: "调查人员" },
  { cat: "阅读生词", src: "③ 2017", en: "sneak", zh: "偷偷携带；溜" },
  { cat: "阅读生词", src: "③ 2017", en: "fake", zh: "假的；假货" },
  { cat: "阅读生词", src: "③ 2017", en: "anticipate", zh: "预料，预期" },
  { cat: "阅读生词", src: "③ 2017", en: "screeners", zh: "安检人员" },
  { cat: "阅读生词", src: "③ 2017", en: "overpack", zh: "过度打包（行李）" },
  { cat: "阅读生词", src: "③ 2017", en: "fees", zh: "费用" },
  { cat: "阅读生词", src: "③ 2017", en: "dispute", zh: "争辩；争端" },
  { cat: "阅读生词", src: "③ 2017", en: "remodeling", zh: "改造，翻新" },
  { cat: "阅读生词", src: "③ 2017", en: "enroll", zh: "注册，登记" },
  { cat: "阅读生词", src: "③ 2017", en: "eligible", zh: "有资格的，合格的" },
  { cat: "阅读生词", src: "③ 2017", en: "expedited", zh: "加急的；v. 加快" },
  { cat: "阅读生词", src: "③ 2017", en: "involved", zh: "涉及的；复杂的" },
  { cat: "阅读生词", src: "③ 2017", en: "upcoming", zh: "即将到来的" },
  { cat: "阅读生词", src: "③ 2017", en: "Congress", zh: "（美国）国会" },
  { cat: "阅读生词", src: "③ 2017", en: "diverting", zh: "转移，挪用" },
  { cat: "阅读生词", src: "③ 2017", en: "suffers", zh: "遭受，忍受" },
  { cat: "阅读生词", src: "③ 2017", en: "Mediterranean Sea", zh: "地中海" },
  { cat: "阅读生词", src: "③ 2017", en: "Hawaiians", zh: "夏威夷人" },
  { cat: "阅读生词", src: "③ 2017", en: "astronomers", zh: "天文学家" },
  { cat: "阅读生词", src: "③ 2017", en: "reigning", zh: "在位的，当政的" },
  { cat: "阅读生词", src: "③ 2017", en: "monarch", zh: "君主，帝王" },
  { cat: "阅读生词", src: "③ 2017", en: "esteemed", zh: "受尊敬的；尊重" },
  { cat: "阅读生词", src: "③ 2017", en: "worshiped", zh: "崇拜，敬奉" },
  { cat: "阅读生词", src: "③ 2017", en: "revolutionize", zh: "使发生根本变革" },
  { cat: "阅读生词", src: "③ 2017", en: "cosmos", zh: "宇宙" },
  { cat: "阅读生词", src: "③ 2017", en: "dormant", zh: "休眠的，蛰伏的" },
  { cat: "阅读生词", src: "③ 2017", en: "volcano", zh: "火山" },
  { cat: "阅读生词", src: "③ 2017", en: "observatory", zh: "天文台，观测台" },
  { cat: "阅读生词", src: "③ 2017", en: "unmatched", zh: "无与伦比的" },
  { cat: "阅读生词", src: "③ 2017", en: "clarity", zh: "清晰度，清澈" },
  { cat: "阅读生词", src: "③ 2017", en: "bulky", zh: "庞大的，笨重的" },
  { cat: "阅读生词", src: "③ 2017", en: "disrespect", zh: "不敬，无礼" },
  { cat: "阅读生词", src: "③ 2017", en: "contrary", zh: "相反的" },
  { cat: "阅读生词", src: "③ 2017", en: "relic", zh: "遗物，遗迹" },
  { cat: "阅读生词", src: "③ 2017", en: "sacred", zh: "神圣的" },
  { cat: "阅读生词", src: "③ 2017", en: "sovereign", zh: "主权的，拥有主权的" },
  { cat: "阅读生词", src: "③ 2017", en: "holiness", zh: "神圣" },
  { cat: "阅读生词", src: "③ 2017", en: "renaissance", zh: "复兴，文艺复兴" },
  { cat: "阅读生词", src: "③ 2017", en: "curiosity", zh: "好奇心" },
  { cat: "阅读生词", src: "③ 2017", en: "primordial", zh: "原始的，最初的" },
  { cat: "阅读生词", src: "③ 2017", en: "ancestral", zh: "祖先的" },
  { cat: "阅读生词", src: "③ 2017", en: "archaeological", zh: "考古学的" },
  { cat: "阅读生词", src: "③ 2017", en: "heritage", zh: "遗产，传统" },
  { cat: "阅读生词", src: "③ 2017", en: "minimize", zh: "使最小化，减到最少" },
  { cat: "阅读生词", src: "③ 2017", en: "visibility", zh: "能见度，可见性" },
  { cat: "阅读生词", src: "③ 2017", en: "fragile", zh: "脆弱的，易碎的" },
  { cat: "阅读生词", src: "③ 2017", en: "dawn", zh: "黎明，破晓" },
  { cat: "阅读生词", src: "③ 2017", en: "starry", zh: "布满星星的" },
  { cat: "阅读生词", src: "③ 2017", en: "policymakers", zh: "政策制定者" },
  { cat: "阅读生词", src: "③ 2017", en: "usefulness", zh: "有用性，实用性" },
  { cat: "阅读生词", src: "③ 2017", en: "annoyed", zh: "恼怒的，生气的" },
  { cat: "阅读生词", src: "③ 2017", en: "flawed", zh: "有缺陷的，有瑕疵的" },
  { cat: "阅读生词", src: "③ 2017", en: "concept", zh: "概念，观念" },
  { cat: "阅读生词", src: "③ 2017", en: "prospects", zh: "前景，前途" },
  { cat: "阅读生词", src: "③ 2017", en: "convert", zh: "转换，转变" },
  { cat: "阅读生词", src: "③ 2017", en: "criteria", zh: "标准，准则" },
  { cat: "阅读生词", src: "③ 2017", en: "engagement", zh: "参与；交往" },
  { cat: "阅读生词", src: "③ 2017", en: "indicators", zh: "指标，标志" },
  { cat: "阅读生词", src: "③ 2017", en: "equality", zh: "平等，均等" },
  { cat: "阅读生词", src: "③ 2017", en: "well-being", zh: "福祉，幸福安康" },
  { cat: "阅读生词", src: "③ 2017", en: "budding", zh: "崭露头角的；发芽的" },
  { cat: "阅读生词", src: "③ 2017", en: "forecasted", zh: "预见的，预测的" },
  { cat: "阅读生词", src: "③ 2017", en: "doom", zh: "厄运，劫难" },
  { cat: "阅读生词", src: "③ 2017", en: "misinterpreted", zh: "误解，曲解" },
  { cat: "阅读生词", src: "③ 2017", en: "defied", zh: "违抗，挑战" },
  { cat: "阅读生词", src: "③ 2017", en: "reluctant", zh: "不情愿的，勉强的" },
  { cat: "阅读生词", src: "③ 2017", en: "remold", zh: "重塑，改造" },
  { cat: "阅读生词", src: "③ 2017", en: "sponsored", zh: "赞助，资助" },
  { cat: "阅读生词", src: "③ 2017", en: "inadequate", zh: "不充分的，不足的" },
  { cat: "阅读生词", src: "③ 2017", en: "Brexit", zh: "英国脱欧" },
  { cat: "阅读生词", src: "③ 2017", en: "unanimous", zh: "一致同意的" },
  { cat: "阅读生词", src: "③ 2017", en: "conviction", zh: "定罪，判罪" },
  { cat: "阅读生词", src: "③ 2017", en: "governor", zh: "州长；行长" },
  { cat: "阅读生词", src: "③ 2017", en: "ethics", zh: "伦理，道德" },
  { cat: "阅读生词", src: "③ 2017", en: "jury", zh: "陪审团" },
  { cat: "阅读生词", src: "③ 2017", en: "unsettled", zh: "未解决的，悬而未决的" },
  { cat: "阅读生词", src: "③ 2017", en: "duties", zh: "职责，义务" },
  { cat: "阅读生词", src: "③ 2017", en: "intent", zh: "意图，目的" },
  { cat: "阅读生词", src: "③ 2017", en: "justices", zh: "大法官；法官" },
  { cat: "阅读生词", src: "③ 2017", en: "distasteful", zh: "令人反感的" },
  { cat: "阅读生词", src: "③ 2017", en: "nasty", zh: "恶劣的，令人厌恶的" },
  { cat: "阅读生词", src: "③ 2017", en: "favoritism", zh: "偏袒，任人唯亲" },
  { cat: "阅读生词", src: "③ 2017", en: "bureaucratic", zh: "官僚的，官僚主义的" },
  { cat: "阅读生词", src: "③ 2017", en: "prosecution", zh: "起诉，检举" },
  { cat: "阅读生词", src: "③ 2017", en: "bribery", zh: "贿赂，行贿" },
  { cat: "阅读生词", src: "③ 2017", en: "constituents", zh: "选民，选区居民" },
  { cat: "阅读生词", src: "③ 2017", en: "reinforces", zh: "加强，强化" },
  { cat: "阅读生词", src: "③ 2017", en: "integrity", zh: "诚信，正直" },
  { cat: "阅读生词", src: "③ 2017", en: "transparency", zh: "透明度" },
  { cat: "阅读生词", src: "③ 2017", en: "perceptions", zh: "认知，看法" },
  { cat: "阅读生词", src: "③ 2017", en: "premise", zh: "前提，假设" },
  { cat: "阅读生词", src: "③ 2017", en: "democratic", zh: "民主的" },
  { cat: "阅读生词", src: "③ 2017", en: "contemptuous", zh: "轻蔑的，藐视的" },
  { cat: "阅读生词", src: "③ 2017", en: "corruptive", zh: "腐败的，败坏性的" },
  { cat: "阅读生词", src: "③ 2017", en: "sizable", zh: "相当大的" },
  { cat: "阅读生词", src: "③ 2017", en: "intentionally", zh: "故意地" },
  { cat: "阅读生词", src: "③ 2017", en: "assumption", zh: "假设，前提" },
  { cat: "阅读生词", src: "③ 2017", en: "exempt", zh: "免除，豁免" },
  { cat: "阅读生词", src: "③ 2017", en: "conscience", zh: "良心，良知" },
  { cat: "阅读生词", src: "③ 2017", en: "sarcastic", zh: "讽刺的，嘲讽的" },
  { cat: "阅读生词", src: "③ 2017", en: "skeptical", zh: "怀疑的" },
  { cat: "阅读生词", src: "③ 2017", en: "tolerant", zh: "宽容的" },
  { cat: "阅读生词", src: "③ 2017", en: "supportive", zh: "支持的" },
  { cat: "阅读短语", src: "③ 2017", en: "combined with", zh: "与……结合，连同" },
  { cat: "阅读短语", src: "③ 2017", en: "screening lanes", zh: "安检通道" },
  { cat: "阅读短语", src: "③ 2017", en: "win-win", zh: "双赢的" },
  { cat: "阅读短语", src: "③ 2017", en: "sticker shock", zh: "（面对高昂标价的）震惊" },
  { cat: "阅读短语", src: "③ 2017", en: "fatal flaw", zh: "致命缺陷" },
  { cat: "阅读短语", src: "③ 2017", en: "unanimous ruling", zh: "一致裁决" },
  { cat: "阅读短语", src: "③ 2017", en: "dormant volcano", zh: "休眠火山" },
  { cat: "阅读短语", src: "③ 2017", en: "sovereign nation", zh: "主权国家" },
  { cat: "阅读短语", src: "③ 2017", en: "cultural heritage", zh: "文化遗产" },
  { cat: "阅读短语", src: "③ 2017", en: "equality of access to", zh: "平等获取……的机会" },
  { cat: "阅读短语", src: "③ 2017", en: "campaign donation", zh: "竞选捐款" },
  { cat: "阅读短语", src: "③ 2017", en: "rules on lobbying", zh: "游说规则" },
  { cat: "阅读短语", src: "③ 2017", en: "anti-bribery laws", zh: "反贿赂法" },
  { cat: "阅读短语", src: "③ 2017", en: "no longer regarded as", zh: "不再被视为" },
  { cat: "阅读短语", src: "③ 2017", en: "rather than", zh: "而不是" },
  { cat: "阅读短语", src: "③ 2017", en: "a number of", zh: "许多，若干" }
];
